### ISSUE TITLE
Progress Tracking: Document Every Token

### ISSUE THREAD

**Issue by rpitasky** [TI-Toolkit/tokens-wiki#1]
Contributors: Check the box to claim the token.
- [x] ►DMS
- [x] ►Dec
- [x] ►Frac
- [ ] →
- [ ] Boxplot
- [ ] [
- [ ] ]
- [ ] {
- [ ] }
- [ ] ʳ
- [ ] °
- [ ] ˉ¹
- [ ] ²
- [ ] ᵀ
- [ ] ³
- [ ] (
- [ ] )
- [ ] round(
- [ ] pxl-Test(
- [ ] augment(
- [ ] rowSwap(
- [ ] row+(
- [ ] *row(
- [ ] *row+(
- [ ] max(
- [ ] min(
- [ ] R►Pr(
- [ ] R►Pθ(
- [ ] P►Rx(
- [ ] P►Ry(
- [ ] median(
- [ ] randM(
- [ ] mean(
- [ ] solve(
- [ ] seq(
- [ ] fnInt(
- [ ] nDeriv(
- [ ] fMin(
- [ ] fMax(
- [ ] "
- [ ] ,
- [ ] [i]
- [ ] !
- [ ] CubicReg 
- [ ] QuartReg 
- [ ] 0-9
- [ ] .
- [ ] ᴇ
- [ ]  or 
- [ ]  xor 
- [ ] :
- [ ]  and 
- [ ] A-θ
- [ ] [A]-[J]
- [ ] L₁-L₆
- [ ] Y₁-Y₀
- [ ] X₁ᴛ,Y₁ᴛ-X₆ᴛ,Y₆ᴛ
- [ ] r₁-r₆
- [ ] |u, |v, |w
- [ ] prgm
- [ ] Pic1-Pic0
- [ ] GDB1-GDB0
- [ ] [RegEQ]
- [ ] [n]
- [ ] ẋ
- [ ] Σx
- [ ] Σx²
- [ ] [Sx]
- [ ] σx
- [ ] [minX]
- [ ] [maxX]
- [ ] [minY]
- [ ] [maxY]
- [ ] ȳ
- [ ] Σy
- [ ] Σy²
- [ ] [Sy]
- [ ] σy
- [ ] Σxy
- [ ] [r]
- [ ] [Med]
- [ ] [Q1]
- [ ] [Q3]
- [ ] [|a]
- [ ] [|b]
- [ ] [|c]
- [ ] [|d]
- [ ] [|e]
- [ ] x₁,y₁-x₃,y₃
- [ ] [recursiven]
- [ ] [p]
- [ ] [z]
- [ ] [t]
- [ ] χ²
- [ ] [|F]
- [ ] [df]
- [ ] [ṗ]
- [ ] ṗ₁
- [ ] ṗ₂
- [ ] ẋ₁
- [ ] Sx₁
- [ ] n₁
- [ ] ẋ₂
- [ ] Sx₂
- [ ] n₂
- [ ] [Sxp]
- [ ] [lower]
- [ ] [upper]
- [ ] [s]
- [ ] r²
- [ ] R²
- [ ] [factordf]
- [ ] [factorSS]
- [ ] [factorMS]
- [ ] [errordf]
- [ ] [errorSS]
- [ ] [errorMS]
- [ ] ZXscl
- [ ] ZYscl
- [ ] Xscl
- [ ] Yscl
- [ ] UnStart
- [ ] u(nMin)
- [ ] VnStart
- [ ] v(nMin)
- [ ] Un-₁
- [ ] Vn-₁
- [ ] Zu(nmin)
- [ ] Zv(nmin)
- [ ] Xmin
- [ ] Xmax
- [ ] Ymin
- [ ] Ymax
- [ ] Tmin
- [ ] Tmax
- [ ] θMin
- [ ] θMax
- [ ] ZXmin
- [ ] ZXmax
- [ ] ZYmin
- [ ] ZYmax
- [ ] Zθmin
- [ ] Zθmax
- [ ] ZTmin
- [ ] ZTmax
- [ ] TblStart
- [ ] nMin
- [ ] PlotStart
- [ ] ZPlotStart
- [ ] nMax
- [ ] ZnMax
- [ ] nStart
- [ ] nMin
- [ ] ZnMin
- [ ] ∆Tbl
- [ ] Tstep
- [ ] θstep
- [ ] ZTstep
- [ ] Zθstep
- [ ] ∆X
- [ ] ∆Y
- [ ] XFact
- [ ] YFact
- [ ] TblInput
- [ ] |N
- [ ] I%
- [ ] PV
- [ ] PMT
- [ ] FV
- [ ] |P/Y
- [ ] |C/Y
- [ ] w(nMin)
- [ ] Zw(nMin)
- [ ] PlotStep
- [ ] ZPlotStep
- [ ] Xres
- [ ] ZXres
- [ ] Radian
- [ ] Degree
- [ ] Normal
- [ ] Sci
- [ ] Eng
- [ ] Float
- [ ] =
- [ ] &lt;
- [ ] &gt;
- [ ] ≤
- [ ] ≥
- [ ] ≠
- [ ] +
- [ ] -
- [ ] Ans
- [ ] Fix
- [ ] Horiz
- [ ] Full
- [ ] Func
- [ ] Param
- [ ] Polar
- [ ] Seq
- [ ] IndpntAuto
- [ ] IndpntAsk
- [ ] DependAuto
- [ ] DependAsk
- [ ] Sequential
- [ ] Simul
- [ ] PolarGC
- [ ] RectGC
- [ ] CoordOn
- [ ] CoordOff
- [ ] Connected
- [ ] Thick
- [ ] Dot
- [ ] Dot-Thick
- [ ] AxesOn
- [ ] AxesOff
- [ ] GridOn
- [ ] GridDot
- [ ] GridOff
- [ ] LabelOn
- [ ] LabelOff
- [ ] Web
- [ ] Time
- [ ] uvAxes
- [ ] vwAxes
- [ ] uwAxes
- [ ] □
- [ ] ﹢
- [ ] ·
- [ ] *
- [ ] /
- [ ] Trace
- [ ] ClrDraw
- [ ] ZStandard
- [ ] ZTrig
- [ ] ZBox
- [ ] Zoom In
- [ ] Zoom Out
- [ ] ZSquare
- [ ] ZInteger
- [ ] ZPrevious
- [ ] ZDecimal
- [ ] ZoomStat
- [ ] ZoomRcl
- [ ] PrintScreen
- [ ] ZoomSto
- [ ] Text(
- [ ] nPr
- [ ] nCr
- [ ] FnOn
- [ ] FnOff
- [ ] StorePic
- [ ] RecallPic
- [ ] StoreGDB
- [ ] RecallGDB
- [ ] Line(
- [ ] Vertical
- [ ] Pt-On(
- [ ] Pt-Off(
- [ ] Pt-Change(
- [ ] Pxl-On(
- [ ] Pxl-Off(
- [ ] Pxl-Change(
- [ ] Shade(
- [ ] Circle(
- [ ] Horizontal
- [ ] Tangent(
- [ ] DrawInv 
- [ ] DrawF 
- [ ] Str1-Str0
- [ ] rand
- [ ] π
- [ ] getKey
- [ ] '
- [ ] ?
- [ ] ⁻
- [ ] int 
- [ ] int(
- [ ] abs 
- [ ] abs(
- [ ] det 
- [ ] det(
- [ ] identity 
- [ ] identity(
- [ ] dim 
- [ ] dim(
- [ ] sum 
- [ ] sum(
- [ ] prod(
- [ ] not(
- [ ] iPart 
- [ ] iPart(
- [ ] fPart 
- [ ] fPart(
- [ ] npv(
- [ ] irr(
- [ ] bal(
- [ ] ΣPrn(
- [ ] ΣInt(
- [ ] ►Nom(
- [ ] ►Eff(
- [ ] dbd(
- [ ] lcm(
- [ ] gcd(
- [ ] randInt(
- [ ] randBin(
- [ ] sub(
- [ ] stdDev(
- [ ] variance(
- [ ] inString(
- [ ] normalcdf(
- [ ] invNorm(
- [ ] tcdf(
- [ ] χ²cdf(
- [ ] Fcdf(
- [ ] binompdf(
- [ ] binomcdf(
- [ ] poissonpdf(
- [ ] poissoncdf(
- [ ] geometpdf(
- [ ] geometcdf(
- [ ] normalpdf(
- [ ] tpdf(
- [ ] χ²pdf(
- [ ] Fpdf(
- [ ] randNorm(
- [ ] tvm_Pmt
- [ ] tvm_I%
- [ ] tvm_PV
- [ ] tvm_N
- [ ] tvm_FV
- [ ] conj(
- [ ] real(
- [ ] imag(
- [ ] angle(
- [ ] cumSum(
- [ ] expr(
- [ ] length(
- [ ] DeltaList(
- [ ] ref(
- [ ] rref(
- [ ] ►Rect
- [ ] ►Polar
- [ ] [e]
- [ ] SinReg
- [ ] Logistic
- [ ] LinRegTTest
- [ ] ShadeNorm(
- [ ] Shade_t(
- [ ] Shadeχ²(
- [ ] ShadeF(
- [ ] Matr►list(
- [ ] List►matr(
- [ ] Z-Test(
- [ ] T-Test
- [ ] 2-SampZTest(
- [ ] 1-PropZTest(
- [ ] 2-PropZTest(
- [ ] χ²-Test(
- [ ] ZInterval
- [ ] 2-SampZInt(
- [ ] 1-PropZInt(
- [ ] 2-PropZInt(
- [ ] GraphStyle(
- [ ] 2-SampTTest
- [ ] 2-SampFTest
- [ ] TInterval
- [ ] 2-SampTInt
- [ ] SetUpEditor 
- [ ] Pmt_End
- [ ] Pmt_Bgn
- [ ] Real
- [ ] re^θi
- [ ] a+bi
- [ ] ExprOn
- [ ] ExprOff
- [ ] ClrAllLists
- [ ] GetCalc(
- [ ] DelVar
- [ ] Equ►String(
- [ ] String►Equ(
- [ ] Clear Entries
- [ ] Select(
- [ ] ANOVA(
- [ ] ModBoxPlot
- [ ] NormProbPlot
- [ ] G-T
- [ ] ZoomFit
- [ ] DiagnosticOn
- [ ] DiagnosticOff
- [ ] Archive 
- [ ] UnArchive 
- [ ] Asm(
- [ ] AsmComp(
- [ ] AsmPrgm
- [ ] Accented Letters
- [ ] Greek letters, symbols, lowercase letters
- [ ] GarbageCollect
- [ ] √(
- [ ] ³√
- [ ] ³√(
- [ ] ln(
- [ ] e^
- [ ] e^(
- [ ] log(
- [ ] ₁₀^(
- [ ] sin(
- [ ] sin⁻¹(
- [ ] cos(
- [ ] cos⁻¹(
- [ ] tan(
- [ ] tan⁻¹(
- [ ] sinh(
- [ ] sinh⁻¹(
- [ ] cosh(
- [ ] cosh⁻¹(
- [ ] tanh(
- [ ] tanh⁻¹(
- [ ] If 
- [ ] Then
- [ ] Else
- [ ] While 
- [ ] Repeat 
- [ ] For(
- [ ] End
- [ ] Return
- [ ] Lbl 
- [ ] Goto 
- [ ] Pause 
- [ ] Stop
- [ ] IS&gt;(
- [ ] DS&lt;(
- [ ] Input 
- [ ] Prompt 
- [ ] Disp 
- [ ] DispGraph
- [ ] Output(
- [ ] ClrHome
- [ ] Fill(
- [ ] SortA(
- [ ] SortD(
- [ ] DispTable
- [ ] Menu(
- [ ] Send(
- [ ] Get(
- [ ] PlotsOn
- [ ] PlotsOff
- [ ] ʟ
- [ ] Plot1(
- [ ] Plot2(
- [ ] Plot3(
- [ ] setDate(
- [ ] setTime(
- [ ] checkTmr(
- [ ] setDtFmt(
- [ ] setTmFmt(
- [ ] timeCnv(
- [ ] dayOfWk(
- [ ] getDtStr(
- [ ] getTmStr(
- [ ] getDate
- [ ] getTime
- [ ] startTmr
- [ ] getDtFmt
- [ ] getTmFmt
- [ ] isClockOn
- [ ] ClockOff
- [ ] ClockOn
- [ ] OpenLib(
- [ ] ExecLib
- [ ] invT(
- [ ] χ²GOF-Test(
- [ ] LinRegTInt
- [ ] Manual-Fit
- [ ] ZQuadrant1
- [ ] ZFrac1/2
- [ ] ZFrac1/3
- [ ] ZFrac1/4
- [ ] ZFrac1/5
- [ ] ZFrac1/8
- [ ] ZFrac1/10
- [ ] mathprintbox
- [ ] ⁄
- [ ] ᵤ
- [ ] ►n⁄d◄►Un⁄d
- [ ] ►F◄►D
- [ ] remainder(
- [ ] Σ(
- [ ] logBASE(
- [ ] randIntNoRep(
- [ ] [MATHPRINT]
- [ ] [CLASSIC]
- [ ] n⁄d
- [ ] Un⁄d
- [ ] [AUTO]
- [ ] [DEC]
- [ ] [FRAC]
- [ ] BLUE
- [ ] RED
- [ ] BLACK
- [ ] MAGENTA
- [ ] GREEN
- [ ] ORANGE
- [ ] BROWN
- [ ] NAVY
- [ ] LTBLUE
- [ ] YELLOW
- [ ] WHITE
- [ ] LTGREY
- [ ] MEDGREY
- [ ] GREY
- [ ] DARKGREY
- [ ] GridLine
- [ ] BackgroundOn
- [ ] BackgroundOff
- [ ] GraphColor(
- [ ] TextColor(
- [ ] Asm84CPrgm
- [ ] DetectAsymOn
- [ ] DetectAsymOff
- [ ] BorderColor
- [ ] plottinydot
- [ ] Thin
- [ ] Dot-Thin
- [ ] PlySmlt2
- [ ] Asm84CEPrgm
- [ ] u(n-2)
- [ ] v(n-2)
- [ ] w(n-2)
- [ ] u(n-1)
- [ ] v(n-1)
- [ ] w(n-1)
- [ ] u(n)
- [ ] v(n)
- [ ] w(n)
- [ ] u(n+1)
- [ ] v(n+1)
- [ ] w(n+1)
- [ ] pieceWise(
- [ ] SEQ(n)
- [ ] SEQ(n+1)
- [ ] SEQ(n+2)
- [ ] LEFT
- [ ] CENTER
- [ ] RIGHT
- [ ] invBinom(
- [ ] Wait
- [ ] toString(
- [ ] eval(
- [ ] Execute Program
- [ ] Undo Clear
- [ ] Insert Line Above
- [ ] Cut Line
- [ ] Copy Line
- [ ] Paste Line Below
- [ ] Insert Comment Above
- [ ] Quit Editor
- [ ] piecewise(
- [ ] ^
- [ ] ˣ√
- [ ] 1-Var Stats
- [ ] 2-Var Stats
- [ ] LinReg(a+bx) 
- [ ] ExpReg 
- [ ] LnReg 
- [ ] PwrReg 
- [ ] Med-Med 
- [ ] QuadReg 
- [ ] ClrList 
- [ ] ClrTable
- [ ] Histogram
- [ ] xyLine
- [ ] Scatter
- [ ] LinReg(ax+b)
